version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:1.11
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: add channel
          command: nix-channel --add https://nixos.org/channels/nixpkgs nixpkgs
      - run:
          name: nix-build
          command: nix-build .
